version: "3.9" #version of docker-compose
  services:
    db:
      container_name: mariadb
      image: docker.io/library/mariadb:10.3
      ports:
      - "3306:3306"
      environment:
        - MARIADB_ROOT_PASSWORD=root                    #default password of the MySQL container
      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro          #database files called when the container is built and started for the first time
    web:
      container_name: tomcat
      build:
        context: .                                      # get context path
        dockerfile: tomcat.Dockerfile
      ports:
        - "8080:8080"
